# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PoshBot
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  PoshBot - A chat bot written in PowerShell
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://poshbot.io" # the base hostname & protocol for your site
enforce_ssl: poshbot.io
twitter_username: devblackops
github_username:  devblackops

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']